In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# getting the data frame from git 
url = 'https://raw.githubusercontent.com/JishnuJayaraj/PA/master/Batcave/NN/Keras/4_test/button1.csv'
dataset = pd.read_csv(url)

#print(dataset)
# matrix of features and matrix of target variable(only taking project and element)
# feature vector, all rows except 1st(index) and the last column (predict value)
X = dataset.iloc[:, 2:4].values
# class (predicting column)
y = dataset.iloc[:, 4].values

#print(X)
#print(y)


# Label encoder to encode the project name (A,B,C) and elements (button,table...)
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

labelencoder_X_1 = LabelEncoder()
X[:, 0] = labelencoder_X_1.fit_transform(X[:, 0])
labelencoder_X_2 = LabelEncoder()
X[:, 1] = labelencoder_X_2.fit_transform(X[:, 1])

# finding corresponding integer index for each string values
# A-0,B-1,... button-0,header-2,...
print(X)

# convert the label encoder to matrix form
onehotencoder1 = OneHotEncoder(categorical_features = [0,1])
X = onehotencoder1.fit_transform(X).toarray()

print(X)

[[0 0]
 [1 3]
 [0 2]
 [0 1]
 [2 4]
 [1 2]
 [2 0]
 [0 4]
 [1 4]
 [0 3]]
[[1. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1. 0.]]


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [0]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1)

#print(X_train)

# Feature Scaling, not needed for now(already only 0's an 1's) but still done
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)



[[ 1.11803399 -0.70710678 -0.53452248 -0.35355339 -0.35355339 -0.53452248
  -0.53452248  1.41421356]
 [-0.89442719  1.41421356 -0.53452248 -0.35355339 -0.35355339  1.87082869
  -0.53452248 -0.70710678]
 [ 1.11803399 -0.70710678 -0.53452248 -0.35355339 -0.35355339  1.87082869
  -0.53452248 -0.70710678]
 [-0.89442719 -0.70710678  1.87082869  2.82842712 -0.35355339 -0.53452248
  -0.53452248 -0.70710678]
 [ 1.11803399 -0.70710678 -0.53452248 -0.35355339  2.82842712 -0.53452248
  -0.53452248 -0.70710678]
 [-0.89442719 -0.70710678  1.87082869 -0.35355339 -0.35355339 -0.53452248
  -0.53452248  1.41421356]
 [ 1.11803399 -0.70710678 -0.53452248 -0.35355339 -0.35355339 -0.53452248
   1.87082869 -0.70710678]
 [-0.89442719  1.41421356 -0.53452248 -0.35355339 -0.35355339 -0.53452248
  -0.53452248  1.41421356]
 [-0.89442719  1.41421356 -0.53452248 -0.35355339 -0.35355339 -0.53452248
   1.87082869 -0.70710678]]


In [0]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import EarlyStopping

#Initializing Neural Network
classifier = Sequential()



# Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 8))

# Adding the second hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))



# Compiling Neural Network
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])


#set early stopping monitor so the model stops training when it won't improve anymore
#early_stopping_monitor = EarlyStopping(patience=3)


# Fitting our model 
classifier.fit(X_train, y_train, nb_epoch = 30) #, callbacks=[early_stopping_monitor])

#   Get loss and accuracy on test data
eval_result = classifier.evaluate(X_test, y_test)
#   Print test accuracy
print("\n\nTest loss:", eval_result[0], "Test accuracy:", eval_result[1])


''' 
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)


# Creating the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print(cm)
''' 


Using TensorFlow backend.
W0712 11:58:34.254374 139901273888640 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:12: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=8, units=6, kernel_initializer="uniform")`
  if sys.path[0] == '':
W0712 11:58:34.275471 139901273888640 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0712 11:58:34.278385 139901273888640 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

/usr/local/lib/python3.6/dist-pa

NameError: ignored

Interactive namespace is empty.
